language: node_js
sudo: false
node_js:
  - "lts/*"
  - "stable"
install:
  - yarn install
before_script:
  - yarn install --prefix frontend
script:
  - yarn run ci
notifications:
  email:
    on_success: change
    on_failure: always
addons:
  apt:
    update: true